---
# cmdx - task runner
# https://github.com/suzuki-shunsuke/cmdx
tasks:
  - name: test
    short: t
    description: test
    usage: test
    script: go test ./... -race -covermode=atomic
  - name: vet
    short: v
    description: go vet
    usage: go vet
    script: go vet ./...
  - name: lint
    short: l
    description: lint the go code
    usage: lint the go code
    script: golangci-lint run
  - name: release
    short: r
    description: release the new version
    usage: release the new version
    script: |
      git tag -m "chore: release {{.version}}" "{{.version}}"
      git push origin "{{.version}}"
    args:
      - name: version
        required: true
        validate:
          - regexp: "^v\\d+\\.\\d+.\\d+(-\\d+)?$"
  - name: install
    description: go install
    usage: go install
    script: go install ./cmd/tfcmt
  - name: build
    script: |
      tempdir=$(mktemp -d)
      wd=$PWD
      GOOS=linux GOARCH={{.arch}} go build -o "$tempdir/bootstrap" ./cmd/gha-trigger-lambda
      pushd "$tempdir"
      zip "gha-trigger-lambda_linux_{{.arch}}.zip" bootstrap
      mv "gha-trigger-lambda_linux_{{.arch}}.zip" "$wd/terraform"
      popd
      rm -R "$tempdir"
    args:
      - name: arch
        required: false
        default: amd64
        validate:
          - enum:
              - amd64
              - arm64
