---
name: actionlint
on:
  push:
    branches: [main]
    paths:
      - .github/**
      - aqua/actionlint.yaml
  pull_request:
    branches: [main]
    paths:
      - .github/**
      - aqua/actionlint.yaml
jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: aquaproj/aqua-installer@d9c4b5d107a17831a8c8718efa4ce67a0923d1f5 # v2.1.3
        with:
          aqua_version: v2.16.4
      - run: actionlint
