name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - "**.go"
      - ".github/workflows/test.yaml"
      - .golangci.yaml
      - go.mod
      - go.sum
      - aqua/golangci-lint.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3
        with:
          go-version: "1.18.5"

      - uses: aquaproj/aqua-installer@294926f94b4233f202a2f03875c604f840cfed70 # v2.1.1
        with:
          aqua_version: v2.9.0

      - run: golangci-lint run
      - name: Test
        run: go test -v -race ./...

      - name: Run GoReleaser (skip publish)
        uses: goreleaser/goreleaser-action@b508e2e3ef3b19d4e4146d4f8fb3ba9db644a757 # v3
        with:
          version: latest
          args: release --rm-dist --snapshot
