name: test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - "**.go"
      - ".github/workflows/test.yaml"
      - .golangci.yml
      - go.mod
      - go.sum
      - aqua/golangci-lint.yaml
      - aqua/reviewdog.yaml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.18.5"

      - uses: aquaproj/aqua-installer@v1.1.2
        with:
          aqua_version: v1.19.2

      - uses: suzuki-shunsuke/github-action-golangci-lint@v0.1.3
      - name: Test
        run: go test -v -race ./...

      - name: Run GoReleaser (skip publish)
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist --snapshot
